// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-DA4SorWdkFiQv2Qx2bvSCP2dIhICuo',
    appId: '1:637202407686:android:1626f342e7f74c5e5cbe87',
    messagingSenderId: '637202407686',
    projectId: 'go-shop-3',
    databaseURL: 'https://go-shop-3-default-rtdb.firebaseio.com',
    storageBucket: 'go-shop-3.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhtf60wEf-vxH1CIZhHFKrpBH9c3Z4sk',
    appId: '1:637202407686:web:fcbc66857617fdb85cbe87',
    messagingSenderId: '637202407686',
    projectId: 'go-shop-3',
    authDomain: 'go-shop-3.firebaseapp.com',
    databaseURL: 'https://go-shop-3-default-rtdb.firebaseio.com',
    storageBucket: 'go-shop-3.appspot.com',
    measurementId: 'G-YXLHZ5SE5X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBgBWZFfP7GHzwND41yvZKlFoBW635vk',
    appId: '1:637202407686:ios:cff6c9ffe66843fb5cbe87',
    messagingSenderId: '637202407686',
    projectId: 'go-shop-3',
    databaseURL: 'https://go-shop-3-default-rtdb.firebaseio.com',
    storageBucket: 'go-shop-3.appspot.com',
    androidClientId: '637202407686-iacfjibusouj37oubqb2e6m2o2j4t63u.apps.googleusercontent.com',
    iosClientId: '637202407686-7erk9t2vorn0r7lhqdbuegf49er790cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.goShop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBgBWZFfP7GHzwND41yvZKlFoBW635vk',
    appId: '1:637202407686:ios:cff6c9ffe66843fb5cbe87',
    messagingSenderId: '637202407686',
    projectId: 'go-shop-3',
    databaseURL: 'https://go-shop-3-default-rtdb.firebaseio.com',
    storageBucket: 'go-shop-3.appspot.com',
    androidClientId: '637202407686-iacfjibusouj37oubqb2e6m2o2j4t63u.apps.googleusercontent.com',
    iosClientId: '637202407686-7erk9t2vorn0r7lhqdbuegf49er790cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.goShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhtf60wEf-vxH1CIZhHFKrpBH9c3Z4sk',
    appId: '1:637202407686:web:69c662351f3204a15cbe87',
    messagingSenderId: '637202407686',
    projectId: 'go-shop-3',
    authDomain: 'go-shop-3.firebaseapp.com',
    databaseURL: 'https://go-shop-3-default-rtdb.firebaseio.com',
    storageBucket: 'go-shop-3.appspot.com',
    measurementId: 'G-F35Z90KGL9',
  );

}